name = "cuanfans"
compatibility_date = "2024-05-01"
pages_build_output_dir = "public"
[[d1_databases]]
binding = "DB" # HARUS "DB" agar c.env.DB berfungsi
database_name = "cuanfans"
database_id = "7d7e716e-8f04-49a0-81e0-ae35ad904226"
